/* ============================================================
   Build the art the four wargames draw with.

   The source is Game Icons (game-icons.net) via the npm package
   @iconify-json/game-icons: several thousand hand-drawn game icons
   by Lorc, Delapouite and contributors, licensed CC BY 3.0. They are
   real artwork, drawn by illustrators, and they are a very long way
   better than anything that could be hand-rolled in path data here.

   Two outputs:

     js/games/_shared/icons.js   the ~40 icons the games actually use,
                                 as path data, so the site has no
                                 runtime dependency on npm at all
     img/salient/*.png           rendered sprites for Salient, which
                                 is the one skin with baked lighting

   ATTRIBUTION is not optional under CC BY. It is carried in the
   generated file, in CREDITS.md, and on every game page.

     npm install @iconify-json/game-icons sharp
     node tools/build-art.mjs
   ============================================================ */
import {createRequire} from 'node:module';
import {writeFile, mkdir} from 'node:fs/promises';
import sharp from 'sharp';

const require = createRequire(import.meta.url);
const SET = require('@iconify-json/game-icons/icons.json');
const GRID = SET.width || 512;

/* Every icon any game uses, by the name it is known by in the games.
   Kept in one list so a missing name fails the build rather than
   silently drawing nothing. */
const USED = {
  /* Salient — a mid-century army */
  'sal-gen': 'medal',
  'sal-stf': 'walkie-talkie',
  'sal-inf': 'brodie-helmet',
  'sal-arm': 'battle-tank',
  'sal-art': 'field-gun',
  'sal-eng': 'trench-spade',
  'sal-rec': 'jeep',
  'sal-dep': 'cargo-crate',

  /* Tideline — a classical one */
  'tid-gen': 'crown',
  'tid-inf': 'bordered-shield',
  'tid-arm': 'mounted-knight',
  'tid-art': 'catapult',
  'tid-mil': 'spears',

  /* Breakthrough — the Great War */
  'brk-gen': 'binoculars',
  'brk-inf': 'trench-assault',
  'brk-arm': 'great-war-tank',
  'brk-art': 'mortar',
  'brk-rec': 'walking-scout',
  'brk-mil': 'rifle',

  /* Barbican — a siege */
  'bar-captain':   'knight-banner',
  'bar-levy':      'spears',
  'bar-serjeant':  'crossed-swords',
  'bar-ram':       'siege-ram',
  'bar-trebuchet': 'trebuchet',
  'bar-ladder':    'ladder',
  'bar-miner':     'war-pick',
  'bar-castellan': 'crown',
  'bar-archer':    'archer',
  'bar-guard':     'bordered-shield',
  'bar-knight':    'mounted-knight',

  /* ground, shared */
  'g-woods':  'forest',
  'g-hill':   'hills',
  'g-town':   'village',
  'g-marsh':  'swamp',
  'g-wall':   'stone-wall',
  'g-tower':  'watchtower',
  'g-gate':   'gate',
  'g-rubble': 'broken-wall',
  'g-keep':   'castle',
  'g-bridge': 'stone-bridge',
};

const missing = Object.entries(USED).filter(([, n]) => !SET.icons[n]);
if(missing.length){
  console.error('missing from the icon set:', missing.map(m => m[1]).join(', '));
  process.exit(1);
}

/* ---------- 1. the path data ---------- */
const NOTE = `/* GENERATED by tools/build-art.mjs — do not edit.

   Artwork from Game Icons (https://game-icons.net), by Lorc,
   Delapouite and contributors, used under CC BY 3.0
   (https://creativecommons.org/licenses/by/3.0/). Icons are
   unmodified path data; see CREDITS.md.

   Every path is drawn on a ${GRID}x${GRID} grid. */\n`;

let js = NOTE + '\nexport const GRID = ' + GRID + ';\n\nexport const ICON = {\n';
for(const [key, name] of Object.entries(USED)){
  const body = SET.icons[name].body;
  /* The set stores markup, not a bare path. Keep it whole: a few of
     these icons are two subpaths and cutting them apart loses the
     hole in the middle of a wheel. */
  js += `  '${key}': ${JSON.stringify(body)},\n`;
}
js += '};\n\nexport const SOURCE = ' + JSON.stringify(USED, null, 2) + ';\n';
await mkdir('js/games/_shared', {recursive: true});
await writeFile('js/games/_shared/icons.js', js, 'utf8');
console.log('wrote js/games/_shared/icons.js  (' + Object.keys(USED).length + ' icons)');

/* ---------- 2. Salient's rendered sprites ----------
   A struck enamel badge: a bevelled plate in the army's colour with
   the device raised on it. The lighting is baked into the file, which
   is what separates this skin from the three that are drawn live. */
const PX = 128;

const TEAM = {
  b: {top:'#5E8FD8', mid:'#3A63A8', low:'#1E3A६8'.replace('६','6'), rim:'#16294C', dev:'#F2F6FF'},
  r: {top:'#DE7A62', mid:'#B44532', low:'#7A2418', rim:'#521409', dev:'#FFF3EF'},
};

/* The icon bodies carry fill="currentColor", which beats any fill set
   on a parent group — so the colour has to be handed to them as the
   `color` presentation attribute instead. Everything rendered solid
   black for a whole first pass because of exactly this. */
function badge(iconKey, t){
  const b = SET.icons[USED[iconKey]].body;
  const s = 0.62, off = (GRID * (1 - s)) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${PX}" height="${PX}" viewBox="0 0 ${GRID} ${GRID}">
  <defs>
    <linearGradient id="p" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="${t.top}"/>
      <stop offset=".52" stop-color="${t.mid}"/>
      <stop offset="1" stop-color="${t.low}"/>
    </linearGradient>
    <linearGradient id="gloss" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#fff" stop-opacity=".38"/>
      <stop offset=".46" stop-color="#fff" stop-opacity=".06"/>
      <stop offset=".47" stop-color="#000" stop-opacity="0"/>
      <stop offset="1" stop-color="#000" stop-opacity=".16"/>
    </linearGradient>
  </defs>
  <rect x="30" y="30" width="452" height="452" rx="58" fill="${t.rim}"/>
  <rect x="42" y="42" width="428" height="428" rx="50" fill="url(#p)"/>
  <rect x="42" y="42" width="428" height="428" rx="50" fill="url(#gloss)"/>
  <rect x="58" y="58" width="396" height="396" rx="38" fill="none"
        stroke="#fff" stroke-opacity=".22" stroke-width="5"/>
  <g transform="translate(${off} ${off + GRID * 0.030}) scale(${s})" color="#08101E" opacity=".42">${b}</g>
  <g transform="translate(${off} ${off}) scale(${s})" color="${t.dev}">${b}</g>
</svg>`;
}

/* Ground tiles: a flat field colour with the motif ghosted into it,
   so a board of them reads as terrain rather than as a row of icons. */
/* Bright enough to survive a territory wash on top. The first pass
   used field colours a couple of stops darker and, once one army's
   tint went over them, the whole map turned to the same olive mud
   and neither the terrain nor the front could be read. */
const GROUND = {
  open:   {bg:'#93A56A', ink:'#75873F', icon:null},
  woods:  {bg:'#5F8049', ink:'#3D5B2C', icon:'g-woods'},
  hill:   {bg:'#BCA46B', ink:'#8E7639', icon:'g-hill'},
  town:   {bg:'#C3B189', ink:'#6B5B3C', icon:'g-town'},
  marsh:  {bg:'#83957A', ink:'#5A6C51', icon:'g-marsh'},
  river:  {bg:'#5A93BC', ink:'#3D7099', icon:null},
  ford:   {bg:'#7EB0CE', ink:'#3D7099', icon:'g-bridge'},
  road:   {bg:'#CBB98C', ink:'#A08F5E', icon:null},
};

function tile(kind){
  const g = GROUND[kind];
  const s = 0.58, off = (GRID * (1 - s)) / 2;
  const motif = g.icon
    ? `<g transform="translate(${off} ${off}) scale(${s})" color="${g.ink}" opacity=".9">${SET.icons[USED[g.icon]].body}</g>`
    : '';
  /* a very quiet tooth, so large blocks of one colour do not band */
  const speck = Array.from({length: 26}, (_, i) => {
    const x = (i * 97) % GRID, y = (i * 211) % GRID;
    return `<circle cx="${x}" cy="${y}" r="7" fill="${g.ink}" opacity=".22"/>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${PX}" height="${PX}" viewBox="0 0 ${GRID} ${GRID}">
  <rect width="${GRID}" height="${GRID}" fill="${g.bg}"/>${speck}${motif}</svg>`;
}

const OUT = 'img/salient/';
await mkdir(OUT, {recursive: true});
let n = 0;
for(const key of Object.keys(USED)){
  if(!key.startsWith('sal-')) continue;
  const short = key.slice(4);
  for(const team of ['b', 'r']){
    await sharp(Buffer.from(badge(key, TEAM[team]))).png().toFile(`${OUT}${short}-${team}.png`);
    n++;
  }
}
for(const kind of Object.keys(GROUND)){
  await sharp(Buffer.from(tile(kind))).png().toFile(`${OUT}t-${kind}.png`);
  n++;
}
console.log(`rendered ${n} sprites to ${OUT}`);
