#!/usr/bin/env python3
"""Copy a game's rules into supabase/functions/_shared/ for the edge runtime.

The edge function has to run the same legality checks the browser does.
Rather than write them twice, the browser's rules file is the source and
this copies it verbatim. Run before deploying a function.

    python tools/sync-rules.py          # copy
    python tools/sync-rules.py --check  # fail if the copy is stale
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAIRS = [
    (ROOT / 'js/games/rps-chess/rules.js',
     ROOT / 'supabase/functions/_shared/rps-chess-rules.js'),
]
BANNER = ('/* GENERATED by tools/sync-rules.py from {src} — do not edit.\n'
          '   Edit the source file and re-run the script. */\n')

check = '--check' in sys.argv
stale = []

for src, dst in PAIRS:
    want = BANNER.format(src=src.relative_to(ROOT).as_posix()) + src.read_text(encoding='utf-8')
    have = dst.read_text(encoding='utf-8') if dst.exists() else None
    if want == have:
        print(f'up to date  {dst.relative_to(ROOT).as_posix()}')
        continue
    if check:
        stale.append(dst.relative_to(ROOT).as_posix())
        continue
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(want, encoding='utf-8', newline='\n')
    print(f'copied      {dst.relative_to(ROOT).as_posix()}')

if stale:
    print('STALE: ' + ', '.join(stale) + '\nRun: python tools/sync-rules.py', file=sys.stderr)
    sys.exit(1)
