#!/usr/bin/env python3
"""Copy a game's rules into supabase/functions/_shared/ for the edge runtime.

The edge function has to run the same legality checks the browser does.
Rather than write them twice, the browser's rules file is the source and
this copies it verbatim. Run before deploying a function.

    python tools/sync-rules.py          # copy
    python tools/sync-rules.py --check  # fail if the copy is stale
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHARED = ROOT / 'supabase/functions/_shared'

# Every game whose rules and engine the server needs. The bot runner
# plays with the same engine the browser does, for the same reason the
# verifier replays with the same rules: one source.
GAMES = ['rps-chess', 'anvil', 'salient', 'tideline', 'breakthrough', 'barbican']

# Modules under js/games/_shared/ that a rules file may import. They are
# copied flat alongside everything else. Only the ones the server
# actually needs — counters.js and board.js are interface code and have
# no business in an edge function.
COMMON = ['control.js']

PAIRS = [(ROOT / 'js/games/_shared' / name, SHARED / name) for name in COMMON]
for slug in GAMES:
    PAIRS.append((ROOT / f'js/games/{slug}/rules.js', SHARED / f'{slug}-rules.js'))
for slug in GAMES:
    PAIRS.append((ROOT / f'js/games/{slug}/ai.js', SHARED / f'{slug}-ai.js'))

# The copies live flat in _shared/, so every relative import has to be
# re-pointed as the file is written out. A rules file reaches sideways
# for the shared control field; an ai file reaches for its own rules.
REWRITE = {}
for slug in GAMES:
    REWRITE[f'{slug}-rules.js'] = [("from '../_shared/control.js'", "from './control.js'")]
    REWRITE[f'{slug}-ai.js'] = [
        ("from './rules.js'", f"from './{slug}-rules.js'"),
        ("from '../_shared/control.js'", "from './control.js'"),
    ]
BANNER = ('/* GENERATED by tools/sync-rules.py from {src} — do not edit.\n'
          '   Edit the source file and re-run the script. */\n')

check = '--check' in sys.argv
stale = []

for src, dst in PAIRS:
    body = src.read_text(encoding='utf-8')
    # A rewrite is optional per file: the older two games import nothing
    # sideways, and the newer three do not all import everything.
    for old, new in REWRITE.get(dst.name, []):
        if old in body:
            body = body.replace(old, new)
    want = BANNER.format(src=src.relative_to(ROOT).as_posix()) + body
    have = dst.read_text(encoding='utf-8') if dst.exists() else None
    if want == have:
        print(f'up to date  {dst.relative_to(ROOT).as_posix()}')
        continue
    if check:
        stale.append(dst.relative_to(ROOT).as_posix())
        continue
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(want, encoding='utf-8', newline='\n')
    print(f'copied      {dst.relative_to(ROOT).as_posix()}')

if stale:
    print('STALE: ' + ', '.join(stale) + '\nRun: python tools/sync-rules.py', file=sys.stderr)
    sys.exit(1)
